name: Build and Release LaTeX card

on:
  push:
    tags:
    - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
  
jobs:
  build_release_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: card.tex
          latexmk_use_xelatex: true
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: card.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      
